xen-troops/meta-xt-prod-devel-rpi5

rpi5.yaml
Now the simple Zephyr samples/hello_world app is used as Zen Dom0 example with zero functionality.
This patch switches Dom0 to thin zephyr-dom0-xt application which supports 2 domain cfg domD/DomU and enables xenlib command line interface.
Grygorii Strashko <grygorii_strashko@epam.com>
=> rpi5.yaml: switch to zephyr zephyr-dom0-xt

rpi5.yaml
meta-xt-driver-domain is needed to allow using recipes for backends, such as xen-network.
=> rpi5.yaml: add driver-domain to bblayers

rpi5.yaml
Path "rpi5.yaml: Correct target images for domd" did only half of the job: in changed name of output image for DomD, but it didn't changed dependency name for zephyr-dom0, so now build fails with the following message:
ninja: error: 'yocto/build-domd/tmp/deploy/images/raspberrypi5/Image.bin', needed by 'zephyr/build-dom0/zephyr/zephyr.bin', missing and no known rule to make it
Fix this by providing correct dependency name for Zephyr
Fixes: 3b4eb6839bd7 ("rpi5.yaml: Correct target images for domd")
=> rpi5.yaml: fix zephyr dependencies

rpi5.yaml
Do not use snippet for dom0 as it going to be dropped for zephyr-dom0-xt dom0 application [1].
[1] https://github.com/xen-troops/zephyr-dom0-xt/pull/18
Signed-off-by: Grygorii Strashko <grygorii_strashko@epam.com>
=> rpi5.yaml: drop xen_dom0 snippet for dom0

get_unikraft.sh, rpi5.yaml
Hence SD-card support is added the Zephyr guest domain images need to be
present on SD-card, so add generation of sync and blinky images.
Add unikernel monkey sample image binary to Dom0 storage for demo purposes.
Images stored in default for zephyr-dom0-xt folder "/dom0" on SD-card.
=> Dom0 add generation zephyr domu images and Unicraft sample image

get_unikraft.sh, rpi5.yaml
Moulin provides "http" fetcher to get unikraft binary from an external link.
=> rpi5.yaml: use http fetcher to get unikraft binary

rpi5.yaml
Make domd rootfs on usb by default.
=> rpi5.yaml: Make domd rootfs on usb by default

rpi5.yaml
Now the logs of Zephyr Dom0 and Linux DomD are mixed as they started in parallel by Xen in dom0less mode.
At this stage Zephyr Dom0 logs is more important, so add "quiet" to domd bootargs, so Zephyr Dom0 logs will be seen properly.
=> rpi5.yaml: add "quiet" to domd bootargs

rpi5.yaml
Make partition for dom0 mandatory. Increase this partition size to 512MiB
=> rpi5.yaml: Make partition for dom0 mandatory

rpi5.yaml
Remove rootfs on mmc for domd option. Currently only usb option available.
=> rpi5.yaml: Remove mmc rootfs option

xt-prod-devel-rpi5-domd/recipes-core/image/rpi5-image-xt-domd.bbappend
This change is moved from meta-xt-rpi5. Install all possible kernel modules in case if we need some of them.
---
This PR is complementary to https://github.com/xen-troops/meta-xt-rpi5/pull/18. They need to be fixed together.
=> rpi5-image-xt-domd: install kernel modules to the image

rpi5.yaml
Since the main layer was renamed I have set an actual name to the repo which is meta-xt-prod-devel-rpi5.
=> rpi5.yaml: set actual name for meta-xt-prod-devel-rpi5 repo

rpi5.yaml
Since the main layer was renamed I have set an actual name to the repo which is meta-xt-prod-devel-rpi5.
Reviewed-by: Grygorii Strashko <grygorii_strashko@epam.com>
Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
=> Backport to v0.1: rpi5.yaml: set actual name for meta-xt-prod-devel-rpi5 repo

README.md, rpi5.yaml
Update to the Release v0.1.2:
- fix incompatibility with new rpi5 fw.
=> rpi5.yaml: Release v0.1.2

README.md, rpi5.yaml
Incorporate fixes from meta-xt-rpi5 for the Release v0.2.1 and update Readme.
=> rpi5.yaml: Release v0.2.1

rpi5.yaml
The zephyr-v3.6.0-xt is fully updated to support RPI5 so switch all Zephyr targets to use it.
=> rpi5.yaml: switch zephyr to zephyr-v3.6.0-xt branch

rpi5.yaml
All common data should be kept inside the build folder.
=> yaml: move common_data inside the build directory

layers/xt-prod-devel-rpi5-domd/recipes-core/image/rpi5-image-xt-domd.bbappend, rpi5.yaml
Original code
```
type: raw_image
size: 8 GiB
image_path: "....domd.ext4"
```
worked in this way: the 8GiB partition was created, and rootfs was placed with its original size of about 1GiB. The remaining 7GiB were unusable.
At some point, we made a change to the moulin and started resizing ext4 images to fit the partition of the requested size. However, this resizing happens in the host environment, while the ext4 image is created inside the yocto environment.
Package `e2fsprogs` was upgraded to version 1.47 in the yocto 4.2. And that version uses new options during the creation of the ext4 images. The same version of the `e2fsprogs` is provided with the Ubuntu 23+. At the same time, these new options are not supported by the previous versions of the `e2fsprogs` provided with Ubuntu …
=> yaml: do not resize domd's rootfs

rpi5.yaml
Build on main failed with output
```
Traceback (most recent call last):
File "/home/xtrs/.local/bin/rouge", line 8, in <module>
sys.exit(rouge_entry())
File "/home/xtrs/.local/lib/python3.8/site-packages/moulin/main.py", line 209, in rouge_entry
fileo.truncate(block_entry.size())
File "/home/xtrs/.local/lib/python3.8/site-packages/moulin/rouge/block_entry.py", line 70, in size
self._complete_init()
File "/home/xtrs/.local/lib/python3.8/site-packages/moulin/rouge/block_entry.py", line 94, in _complete_init
partitions = [x._replace(size=x.entry.size()) for x in self._partitions]
File "/home/xtrs/.local/lib/python3.8/site-packages/moulin/rouge/block_entry.py", line 94, in <listcomp>
partitions = [x._replace(size=x.entry.size()) for x in self._partitions]
File …
```
=> Fix linux version mismatch

rpi5.yaml
Stabilize source code for the release v0.3.0.
=> rpi5.yaml: Release v0.3.0

README.md, rpi5.yaml
- add the release tag for meta-xt-common in rpi5.yaml file.
- update implemented features section of README.md
@oleksiimoisieiev
=> Bump release to v0.3.1

README.md, rpi5.yaml
If the CAN_ENABLE is set to yes, the CAN works only with the 2-CH CAN HAT with the MCP2515 chip. Also, in release 0.3.1 of meta-xt-rpi5, a device tree overlay to support the 2 Channel CAN BUS FD Shield with the MCP251XFD chip was added.
Therefore, added the possibility to choose the CAN chip between the previously mentioned two options by setting the `CAN_ENABLE` to `mcp2515` or `seeed_fd` accordingly, which also sets the `DOMD_CAN_TYPE` configuration to enable the required device tree overlay.
Related to: https://github.com/xen-troops/meta-xt-rpi5/pull/41
@firscity @lorc @GrygiriiS @oleksiimoisieiev @rshym
=> yaml: Add CAN support for both chips
